networks:
  gestionale_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  keycloak_data:
    driver: local

services:
  # === TRAEFIK ===
  traefik:
    image: traefik:v3.5.3
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gestionale_network

  # === DATABASE ===
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestionale_network

  # === KEYCLOAK ===
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command:
      - start-dev
      - --hostname-strict=false
      - --hostname-url=http://app.localhost/auth
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import:ro
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`app.localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - gestionale_network

  # === FRONTEND (solo dominio dedicato) ===
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - gestionale_network
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  # === BFF NODE.JS ===
  bff:
    build: ./authBff
    container_name: authBff
    environment:
      - PORT=3001
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=traefik-realm
      - KEYCLOAK_CLIENT_ID=traefik-client
      - KEYCLOAK_CLIENT_SECRET=supersegreto
      - COOKIE_SECRET=12345678901234567890123456789012
    depends_on:
      - keycloak
    networks:
      - gestionale_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bff.rule=Host(`app.localhost`) && PathPrefix(`/authBff`)"
      - "traefik.http.middlewares.prefix-strip.stripprefix.prefixes=/authBff"
      - "traefik.http.routers.bff.entrypoints=web"
      - "traefik.http.services.bff.loadbalancer.server.port=3001"

  # === WHOAMI SERVICE ===
  whoami:
    image: containous/whoami
    container_name: whoami
    networks:
      - gestionale_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app.localhost`) && PathPrefix(`/api/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=secure-api@file"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
