networks:
  gestionale_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  keycloak_data:
    driver: local

services:
  # === TRAEFIK (API Gateway) ===
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"  # Dashboard
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - gestionale_network

  # === DATABASE (PostgreSQL per Keycloak) ===
  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestionale_network

  # === KEYCLOAK (Identity Provider) ===
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command:
      - start-dev
      - --hostname-strict=false
      - --hostname-url=http://keycloak.localhost
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import:ro
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - gestionale_network

  # === FRONTEND (React o simile) ===
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - gestionale_network
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.middlewares=jwt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

      - "traefik.http.routers.frontend-login.rule=Host(`frontend.localhost`) && Path(`/login`)"
      - "traefik.http.routers.frontend-login.entrypoints=web"
      - "traefik.http.routers.frontend-login.middlewares="
