spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheetdb
    username: timesheet_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # per lo sviluppo: crea/aggiorna tabelle. In produzione -> validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  # per validazioni (JSR 380/303)
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
