spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheet
    username: timesheet_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # in dev ricrea schema ogni volta
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always            # esegue data.sql ad ogni avvio

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
