spring:
  datasource:
    url: jdbc:postgresql://db:5432/timesheet?currentSchema=public
    username: timesheet_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # ricrea lo schema ad ogni avvio in dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public  # schema di default per Hibernate

  sql:
    init:
      mode: always            # esegue data.sql ad ogni avvio

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
