http:
  middlewares:
    my-jwt-middleware:
      plugin:
        jwt-validation-middleware:
          secret: ThisIsMyVerySecret
          optional: true
          payloadHeaders:
            X-Custom-Header1: sub
            X-Custom-Header2: name
          authQueryParam: authToken
          authCookieName: authToken
          forwardAuth: false