http:
  middlewares:
    secure-api:
      plugin:
        jwt:
          # Endpoint JWKS di Keycloak
          jwks_urls:
            - "http://keycloak:8080/realms/traefik-realm/protocol/openid-connect/certs"
          
          # Issuer previsto
          issuers:
            - "http://keycloak:8080/realms/traefik-realm"
          
          # Claim obbligatori
          required_claims:
            aud: traefik-client

          # Headers da aggiungere
          JwtHeaders:
            X-User-ID: sub
            X-User-Roles: roles

          jwtSources:
            - type: cookie 
              key: access_token
            
          # Debug
          log_level: debug
    prefix-strip:
      stripPrefix:
        prefixes:
          - "/authBff"