http:
  middlewares:
    spa:
      replacePathRegex:
        regex: ^/(.*)
        replacement: /index.html

    jwt-auth:
      plugin:
        keycloak-jwt:
          jwks_url: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
          audiences: ["frontend-client"]
          claims:
            sub: "X-User-ID"
            role: "X-User-Role"
