log:
  level: INFO

experimental:
  plugins:
    jwt-validation-middleware:
      moduleName: github.com/legege/jwt-validation-middleware
      version: v0.7.1

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true # solo per test locale

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"