FROM node:20-alpine

# Assicuriamoci di essere root
USER root

# Installiamo wget e bash
RUN apk add --no-cache wget bash

# Copiamo lo script e rendiamolo eseguibile
COPY wait-for-keycloak.sh /wait-for-keycloak.sh
RUN chmod +x /wait-for-keycloak.sh

# Directory di lavoro
WORKDIR /app

# Installiamo le dipendenze Node
COPY package*.json ./
RUN npm install --production

COPY . .

EXPOSE 3001

# Eseguiamo prima lo script, poi npm start
CMD ["/bin/sh", "-c", "/wait-for-keycloak.sh && npm start"]