spring:
  datasource:
    url: jdbc:postgresql://db:5432/timesheet
    username: ${DB_USER:timesheet_user}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # in prod non deve ricreare schema
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never          # niente data.sql in prod

logging:
  level:
    root: INFO
