services:
  db:
    image: postgres:15
    container_name: timesheet_db
    environment:
      POSTGRES_DB: timesheet
      POSTGRES_USER: timesheet_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timesheet_user -d timesheet"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: timesheet_app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/timesheet
      SPRING_DATASOURCE_USERNAME: timesheet_user
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: